<svelte:options preserveWhitespace={true}/>
<script>
import {onMount} from 'svelte';
import {lifecycle} from '../shared/lifecycle';
import {CONCEPTS,NW,NH,GN,GE,STATE_SHORT} from './data';
let {learner,graphId,id=undefined,className='',label,manual=false,drawn=false}=$props();
let element,visible=$state(false),focus=$state(null);
const edges=GE.map((e,i)=>{const A=GN[e.a],B=GN[e.b];let path,mx,my;if(e.neg){const x0=A.x,y0=A.y+NH/2,x3=B.x+NW/2+4,y3=B.y;path=`M${x0},${y0} C${x0},${y0+253} ${x3+128},${y3} ${x3},${y3}`;mx=(x0+3*x0+3*(x3+128)+x3)/8;my=(y0+3*(y0+253)+3*y3+y3)/8;}else{const x0=A.x,y0=A.y+NH/2,x3=B.x+(e.bx||0),y3=B.y-NH/2-3,cy=(y0+y3)/2;path=`M${x0},${y0} C${x0},${cy} ${x3},${cy} ${x3},${y3}`;mx=(x0+x3)/2;my=cy;}return {...e,i,path,mx,my,w:e.l.length*6.9+18};});
const near=$derived(new Set([focus,...GE.filter(e=>e.a===focus||e.b===focus).flatMap(e=>[e.a,e.b])]));
$effect(()=>{JSON.stringify(learner.model);focus=null;});
onMount(()=>{const life=lifecycle();if(!manual)life.observe(new IntersectionObserver((es,o)=>es.forEach(e=>{if(e.isIntersecting){visible=true;o.unobserve(e.target)}}),{threshold:.3}),[element]);return life.destroy;});
</script>
<svg bind:this={element} {id} class={'graph '+className} class:drawn={drawn||visible} class:focus={focus!==null} viewBox="0 0 520 462" role="img" aria-label={label}><defs><marker id={graphId+'-ah'} class="mk" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z"/></marker><marker id={graphId+'-ahn'} class="mk neg" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z"/></marker></defs>{#each edges as e}<path class={'e'+(e.neg?' neg':'')} class:hl={focus===e.a||focus===e.b} data-a={e.a} data-b={e.b} d={e.path} pathLength="1" marker-end={'url(#'+graphId+'-ah'+(e.neg?'n':'')+')'} style:--i={e.i}/>{/each}{#each edges as e}<g class={'lab'+(e.neg?' neg':'')} class:hl={focus===e.a||focus===e.b} data-a={e.a} data-b={e.b} style:--i={e.i}><rect x={e.mx-e.w/2} y={e.my-11} width={e.w} height="22" rx="11"/><text x={e.mx} y={e.my+4} text-anchor="middle">{e.l}</text></g>{/each}{#each Object.entries(GN) as [k,n]}{@const st=learner.model[k]}{@const sub='from '+n.src+(st!=='unseen'?' · '+STATE_SHORT[st]:'')}<!-- svelte-ignore a11y_no_noninteractive_tabindex (Focusable source graph nodes preserve the supplied keyboard interaction.) --><g class={'node '+st} class:hl={focus!==null&&near.has(k)} data-k={k} tabindex={manual?-1:0} role="img" aria-label={CONCEPTS[k].name+', '+sub} onmouseenter={()=>focus=k} onmouseleave={()=>focus=null} onfocus={()=>focus=k} onblur={()=>focus=null}><rect class="nb" x={n.x-NW/2} y={n.y-NH/2} width={NW} height={NH} rx="16"/><text class="nt" x={n.x} y={n.y-2} text-anchor="middle">{CONCEPTS[k].name}</text><text class="ns" x={n.x} y={n.y+16} text-anchor="middle">{sub}</text></g>{/each}</svg>
