<svelte:options preserveWhitespace={true}/>
<script>import {NODES,CONCEPTS,VERDICT,STATE_LABEL} from './data';let {learner}=$props();const p=$derived(learner.current);const a=$derived(p&&learner.answerIndex!==null?p.answers[learner.answerIndex]:null);</script>
<ol class="trace" id="trace" aria-labelledby="trace-h">{#each NODES as n,i}<li class="node" class:on={learner.opened[i]} data-n={i+1} data-i={i}><span class="ribbon" aria-hidden="true"></span>
    <div class="k"><span>{n[0]}</span><button type="button" class="src" tabindex={learner.opened[i]?0:-1} onclick={learner.source}>Show source</button></div>
    <p class="hint">{n[1]}</p><div class="v"><div>{#if p}{#if i===0}<p class="quote">“{p.text}”</p><p class="claim">Earth Science Notes, p. 12, {p.n}</p>{:else if i===1}<p class="chips">{#each p.concepts as c}<span class="cpt">{CONCEPTS[c].name}</span>{/each}</p><p class="claim">Claim: {p.claim}</p>{:else if i===2}<p class="edge">{p.edge[0]}<i>{p.edge[1]}</i>{p.edge[2]}</p>{:else if i===3}<p class="act"><b>{p.act.type}</b>{p.act.prompt}</p>{:else if i===4}<ul class="answers">{#each p.answers as answer,k}<li><button type="button" class="ans" data-k={k} aria-pressed={String(learner.answerIndex===k)} onclick={()=>learner.answer(k)}>{answer.t}{#if answer.tag}<small>{answer.tag}</small>{/if}</button></li>{/each}</ul>{:else if i===5&&a}<dl class="judge">
      <dt>Conclusion</dt><dd>{a.read[0]}</dd>
      <dt>Reason</dt><dd>{a.read[1]}</dd>
      <dt>Checks</dt><dd><ul>{#each a.checks as [ok,t]}<li class={ok?'p':'f'}>{t}</li>{/each}</ul></dd>
      <dt>Judge</dt><dd class={'verdict '+VERDICT[a.v].cls}>{VERDICT[a.v].text}</dd></dl>{:else if i===6&&a}<ul class="state">{#each p.concepts as c}<li><span>{CONCEPTS[c].name}</span><span class={'st '+learner.model[c]}>{learner.before[c]===learner.model[c]?STATE_LABEL[learner.model[c]]:STATE_LABEL[learner.before[c]]+' → '+STATE_LABEL[learner.model[c]]}</span></li>{/each}</ul>{/if}{/if}</div></div></li>{/each}</ol>
